controllers:
    resource: ../src/Controller/
    type: annotation
controllers_admin:
    resource: ../src/Administration/Controller
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
